# Generated by Django 5.0.1 on 2024-01-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_user_img_alter_user_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, upload_to='E:\\django_pics'),
        ),
    ]
