# Generated by Django 5.0.1 on 2024-01-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_user_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='likes',
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, default=0, max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
